site_name: SJSU Robotics Research Lab
site_url: https://lphucthinh40.github.io/sample_mkdocs/
theme:
  name: material
  logo: assets/sjsu-logo.png
  palette:
        # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
    - "About Us": 'about.md'
    - Projects:
        - SambotRL:
            - Resources: 'projects/sambotrl_resources.md'
    - Platforms:
        - Optitrack:
            - Overview: 'platforms/optitrack_overview.md'
            - Installation: 'platforms/optitrack_installation.md'
            - "Usage Guide": 'platforms/optitrack_localization.md'
        - ROS: 
            - Overview: 'platforms/ros_overview.md'
            - Installation: 'platforms/ros_installation.md'
            - Cookbook: 'platforms/ros_cookbook.md'
    - Resources:
        - 'Learning ROS': 'resources/learning-ros.md'